spring:
  application:
    name: General
  datasource:
    url: ${DB_URL}
    driver-class-name: org.h2.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2
  jackson:
    time-zone: America/Fortaleza
server:
  port: 8081

jwt:
  private:
    key: classpath:app.key
  public:
    key: classpath:app.pub

tokens:
  expiration:
    access:
      exp: ${ACCESS_T}
    refresh:
      exp: ${REFRESH_T}